# Extracting Positive Patches
#src_csv = '.../CADDYdataset.csv'
#train_images = '.../images/train/'
test_images = './images/test/'
#train_positive_patches = '.../images/train_positive/'
#test_positive_patches = '.../images/test_positive/'
#train_negative_patches = '.../images/train_negative/'
#test_negative_patches = '.../images/test_negative/'
#train_negative_whole = '.../images/train_negative_whole/'
#test_negative_whole = '.../images/test_negative_whole/'
#difficult_patches = '.../images/difficult_patches/'
#train_positive_list = '.../images/train_positive.csv'
#train_negative_list = '.../images/train_negative.csv'
#hnm_list = '.../images/train_hnm.csv'
#train_difficult_patches_list = '.../images/train_difficult_patches.csv'
#train_positive_right_list = '.../images/train_positive_right.csv'
#test_positive_list = '.../images/test_positive.csv'
#test_negative_list = '.../images/test_negative.csv'
#train_dataset_images = '.../images/train_dataset/'
#test_dataset_images = '.../images/test_dataset/'
#x_train_csv = '.../images/x_train.csv'
#y_train_csv = '.../images/y_train.csv'
#x_test_csv = '.../images/x_test.csv'
#y_test_csv = '.../images/y_test.csv'
#prediction_test_csv = '.../images/prediction_test.csv'

# hard negative mining
#hnm_decision_scores = '.../images/hnm_decision_scores.csv'
#hnm_descriptors = '.../images/hnm_descriptors.csv'
#hnm_patchnames = '.../images/hnm_patchnames.csv'
#hnm_images = '.../images/difficult_patches_combined/'
#hnm_images_trimmed = '.../images/train_difficult_patches/'
#hnm_list = '.../images/train_hnm.csv'
#train_difficult_patches_list = '.../images/train_difficult_patches.csv'

models = './models/'

# Results
results = './results/'
visualization_results = './visualization/'
